import { useMutation, useQuery } from "convex/react";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Plus, GripVertical, Bot } from "lucide-react";
import { api } from "../../../convex/_generated/api";
import type { Id } from "../../../convex/_generated/dataModel";
import { cn } from "../../lib/utils";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "../ui/dialog";
import { Button } from "../ui/button";
import { Input } from "../ui/input";

type Status = "backlog" | "todo" | "in_progress" | "done";

type Todo = {
	_id: Id<"workspace_todos">;
	title: string;
	description?: string;
	status: Status;
	order?: number;
	assignee?: "user" | "agent";
	agentPrompt?: string;
};

const COLUMNS: { id: Status; label: string; color: string }[] = [
	{ id: "backlog", label: "Backlog", color: "bg-slate-100 dark:bg-slate-800" },
	{ id: "todo", label: "To Do", color: "bg-blue-50 dark:bg-blue-900/20" },
	{
		id: "in_progress",
		label: "In Progress",
		color: "bg-amber-50 dark:bg-amber-900/20",
	},
	{ id: "done", label: "Done", color: "bg-green-50 dark:bg-green-900/20" },
];

interface KanbanBoardProps {
	workspaceId: Id<"workspaces">;
	onTaskClick?: (todo: Todo) => void;
}

export default function KanbanBoard({
	workspaceId,
	onTaskClick,
}: KanbanBoardProps) {
	const todos = useQuery(api.workspaces.listWorkspaceTodos, { workspaceId });
	const reorderTodo = useMutation(api.workspaces.reorderWorkspaceTodo);
	const createTodo = useMutation(api.workspaces.createWorkspaceTodo);

	const [draggedItem, setDraggedItem] = useState<Todo | null>(null);
	const [dragOverColumn, setDragOverColumn] = useState<Status | null>(null);
	const [createModalOpen, setCreateModalOpen] = useState(false);
	const [createForColumn, setCreateForColumn] = useState<Status>("todo");
	const [newTaskTitle, setNewTaskTitle] = useState("");
	const [isCreating, setIsCreating] = useState(false);

	const todosByColumn = COLUMNS.reduce(
		(acc, col) => {
			acc[col.id] = ((todos as Todo[] | undefined) ?? [])
				.filter((t) => t.status === col.id)
				.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
			return acc;
		},
		{} as Record<Status, Todo[]>,
	);

	const handleDragStart = (e: React.DragEvent, todo: Todo) => {
		setDraggedItem(todo);
		e.dataTransfer.effectAllowed = "move";
		e.dataTransfer.setData("text/plain", todo._id);
	};

	const handleDragOver = (e: React.DragEvent, status: Status) => {
		e.preventDefault();
		setDragOverColumn(status);
	};

	const handleDragLeave = () => {
		setDragOverColumn(null);
	};

	const handleDrop = async (e: React.DragEvent, newStatus: Status) => {
		e.preventDefault();
		if (!draggedItem) return;

		const columnTodos = todosByColumn[newStatus];
		const newOrder =
			columnTodos.length > 0
				? Math.max(...columnTodos.map((t) => t.order ?? 0)) + 1
				: 1;

		await reorderTodo({
			id: draggedItem._id,
			newStatus,
			newOrder,
		});

		setDraggedItem(null);
		setDragOverColumn(null);
	};

	const handleOpenCreateModal = (status: Status) => {
		setCreateForColumn(status);
		setNewTaskTitle("");
		setCreateModalOpen(true);
	};

	const handleCreateTask = async (e: React.FormEvent) => {
		e.preventDefault();
		if (!newTaskTitle.trim()) return;

		setIsCreating(true);
		try {
			await createTodo({
				workspaceId,
				title: newTaskTitle.trim(),
				status: createForColumn,
				autoGenerateDescription: true,
			});
			setNewTaskTitle("");
			setCreateModalOpen(false);
		} catch (error) {
			console.error("Failed to create task:", error);
		} finally {
			setIsCreating(false);
		}
	};

	return (
		<div className="flex gap-4 h-full overflow-x-auto p-4 bg-slate-50/50 dark:bg-slate-900/50">
			{COLUMNS.map((column) => (
				<div
					key={column.id}
					className={cn(
						"flex-shrink-0 w-72 rounded-lg p-3 flex flex-col",
						column.color,
					)}
					onDragOver={(e) => handleDragOver(e, column.id)}
					onDragLeave={handleDragLeave}
					onDrop={(e) => handleDrop(e, column.id)}
				>
					<div className="flex items-center justify-between mb-3">
						<h3 className="font-semibold text-sm flex items-center gap-2">
							{column.label}
							<span className="text-xs opacity-60 bg-white/50 dark:bg-black/20 px-1.5 py-0.5 rounded">
								{todosByColumn[column.id].length}
							</span>
						</h3>
						<button
							type="button"
							onClick={() => handleOpenCreateModal(column.id)}
							className="p-1 hover:bg-white/50 dark:hover:bg-white/10 rounded transition-colors"
							title={`Add task to ${column.label}`}
						>
							<Plus className="w-4 h-4" />
						</button>
					</div>

					<div
						className={cn(
							"flex-1 space-y-2 min-h-[100px] rounded-md transition-colors",
							dragOverColumn === column.id &&
								"bg-blue-100/50 dark:bg-blue-500/10 ring-2 ring-blue-400/50 ring-dashed",
						)}
					>
						<AnimatePresence mode="popLayout">
							{todosByColumn[column.id].map((todo) => (
								<motion.div
									key={todo._id}
									layout
									initial={{ opacity: 0, scale: 0.9 }}
									animate={{ opacity: 1, scale: 1 }}
									exit={{ opacity: 0, scale: 0.9 }}
									draggable
									onDragStart={(e) =>
										handleDragStart(e as unknown as React.DragEvent, todo)
									}
									onDragEnd={() => setDraggedItem(null)}
									onClick={() => onTaskClick?.(todo)}
									className={cn(
										"p-3 bg-white dark:bg-slate-900 rounded-lg shadow-sm border border-slate-200/70 dark:border-white/10 cursor-grab active:cursor-grabbing hover:shadow-md transition-shadow",
										draggedItem?._id === todo._id && "opacity-50",
										todo.assignee === "agent" &&
											"border-l-2 border-l-purple-500",
									)}
								>
									<div className="flex items-start gap-2">
										<GripVertical className="w-4 h-4 text-slate-400 flex-shrink-0 mt-0.5" />
										<div className="flex-1 min-w-0">
											<p className="text-sm font-medium truncate">
												{todo.title}
											</p>
											{todo.description && (
												<p className="text-xs text-slate-500 mt-1 line-clamp-2">
													{todo.description.slice(0, 100)}
													{todo.description.length > 100 ? "..." : ""}
												</p>
											)}
											{todo.assignee === "agent" && (
												<span className="inline-flex items-center gap-1 mt-2 text-xs text-purple-600 dark:text-purple-400">
													<Bot className="w-3 h-3" />
													<span className="w-1.5 h-1.5 rounded-full bg-purple-500 animate-pulse" />
													Queued for Agent
												</span>
											)}
										</div>
									</div>
								</motion.div>
							))}
						</AnimatePresence>

						{todosByColumn[column.id].length === 0 && !dragOverColumn && (
							<div className="text-center text-slate-400 text-xs py-8">
								No tasks
							</div>
						)}
					</div>
				</div>
			))}

			{/* Create Task Modal */}
			<Dialog open={createModalOpen} onOpenChange={setCreateModalOpen}>
				<DialogContent className="max-w-md">
					<DialogHeader>
						<DialogTitle>
							Create Task in {COLUMNS.find((c) => c.id === createForColumn)?.label}
						</DialogTitle>
					</DialogHeader>
					<form onSubmit={handleCreateTask} className="space-y-4">
						<div>
							<Input
								value={newTaskTitle}
								onChange={(e) => setNewTaskTitle(e.target.value)}
								placeholder="Task title..."
								autoFocus
							/>
							<p className="text-xs text-slate-500 mt-2">
								AI will automatically generate a description based on your workspace context.
							</p>
						</div>
						<div className="flex justify-end gap-2">
							<Button
								type="button"
								variant="outline"
								onClick={() => setCreateModalOpen(false)}
							>
								Cancel
							</Button>
							<Button type="submit" disabled={!newTaskTitle.trim() || isCreating}>
								{isCreating ? "Creating..." : "Create Task"}
							</Button>
						</div>
					</form>
				</DialogContent>
			</Dialog>
		</div>
	);
}
