import { useMutation, useQuery } from "convex/react";
import { AnimatePresence, motion } from "framer-motion";
import { Bot, ExternalLink, GitPullRequest, GripVertical, Plus } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { api } from "../convex/_generated/api";
import type { Id } from "../convex/_generated/dataModel";

type Status = "backlog" | "todo" | "in_progress" | "in_review" | "done";

type Todo = {
	_id: Id<"workspace_todos">;
	title: string;
	description?: string;
	status: Status;
	order?: number;
	assignee?: "user" | "agent";
	agentType?: "cursor" | "local";
	agentPrompt?: string;
	currentAgentRunId?: Id<"agent_runs">;
};

const COLUMNS: { id: Status; label: string; color: string }[] = [
	{ id: "backlog", label: "Backlog", color: "bg-slate-100 dark:bg-slate-800" },
	{ id: "todo", label: "To Do", color: "bg-blue-50 dark:bg-blue-900/20" },
	{
		id: "in_progress",
		label: "In Progress",
		color: "bg-amber-50 dark:bg-amber-900/20",
	},
	{
		id: "in_review",
		label: "In Review",
		color: "bg-purple-50 dark:bg-purple-900/20",
	},
	{ id: "done", label: "Done", color: "bg-green-50 dark:bg-green-900/20" },
];

interface KanbanBoardProps {
	workspaceId: Id<"workspaces">;
	onTaskClick?: (todo: Todo) => void;
}

export default function KanbanBoard({
	workspaceId,
	onTaskClick,
}: KanbanBoardProps) {
	const todos = useQuery(api.workspaces.listWorkspaceTodos, { workspaceId });
	const reorderTodo = useMutation(api.workspaces.reorderWorkspaceTodo);
	const createTodo = useMutation(api.workspaces.createWorkspaceTodo);

	const [draggedItem, setDraggedItem] = useState<Todo | null>(null);
	const [dragOverColumn, setDragOverColumn] = useState<Status | null>(null);
	const [createModalOpen, setCreateModalOpen] = useState(false);
	const [createForColumn, setCreateForColumn] = useState<Status>("todo");
	const [newTaskTitle, setNewTaskTitle] = useState("");
	const [isCreating, setIsCreating] = useState(false);

	const todosByColumn = COLUMNS.reduce(
		(acc, col) => {
			acc[col.id] = ((todos as Todo[] | undefined) ?? [])
				.filter((t) => t.status === col.id)
				.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
			return acc;
		},
		{} as Record<Status, Todo[]>,
	);

	const handleDragStart = (e: React.DragEvent, todo: Todo) => {
		setDraggedItem(todo);
		e.dataTransfer.effectAllowed = "move";
		e.dataTransfer.setData("text/plain", todo._id);
	};

	const handleDragOver = (e: React.DragEvent, status: Status) => {
		e.preventDefault();
		setDragOverColumn(status);
	};

	const handleDragLeave = () => {
		setDragOverColumn(null);
	};

	const handleDrop = async (e: React.DragEvent, newStatus: Status) => {
		e.preventDefault();
		if (!draggedItem) return;

		const columnTodos = todosByColumn[newStatus];
		const newOrder =
			columnTodos.length > 0
				? Math.max(...columnTodos.map((t) => t.order ?? 0)) + 1
				: 1;

		await reorderTodo({
			id: draggedItem._id,
			newStatus,
			newOrder,
		});

		setDraggedItem(null);
		setDragOverColumn(null);
	};

	const handleOpenCreateModal = (status: Status) => {
		setCreateForColumn(status);
		setNewTaskTitle("");
		setCreateModalOpen(true);
	};

	const handleCreateTask = async (e: React.FormEvent) => {
		e.preventDefault();
		if (!newTaskTitle.trim()) return;

		setIsCreating(true);
		try {
			await createTodo({
				workspaceId,
				title: newTaskTitle.trim(),
				status: createForColumn,
				autoGenerateDescription: true,
			});
			setNewTaskTitle("");
			setCreateModalOpen(false);
		} catch (error) {
			console.error("Failed to create task:", error);
		} finally {
			setIsCreating(false);
		}
	};

	const getAgentStatusLabel = (todo: Todo) => {
		if (todo.assignee !== "agent") return null;

		// Local agent
		if (todo.agentType === "local") {
			return (
				<span className="inline-flex items-center gap-1 text-xs text-green-600 dark:text-green-400">
					<Bot className="w-3 h-3" />
					Local Agent
				</span>
			);
		}

		if (todo.status === "in_progress" && todo.currentAgentRunId) {
			return (
				<span className="inline-flex items-center gap-1 text-xs text-purple-600 dark:text-purple-400">
					<Bot className="w-3 h-3" />
					<span className="w-1.5 h-1.5 rounded-full bg-purple-500 animate-pulse" />
					Agent Working
				</span>
			);
		}

		if (todo.status === "in_review") {
			return (
				<span className="inline-flex items-center gap-1 text-xs text-purple-600 dark:text-purple-400">
					<GitPullRequest className="w-3 h-3" />
					PR Ready
				</span>
			);
		}

		return (
			<span className="inline-flex items-center gap-1 text-xs text-purple-600 dark:text-purple-400">
				<Bot className="w-3 h-3" />
				Queued for Agent
			</span>
		);
	};

	return (
		<div className="flex gap-4 h-full overflow-x-auto p-4 bg-slate-50/50 dark:bg-slate-900/50">
			{COLUMNS.map((column) => (
				<div
					key={column.id}
					className={cn(
						"flex-shrink-0 w-72 rounded-lg p-3 flex flex-col",
						column.color,
					)}
					onDragOver={(e) => handleDragOver(e, column.id)}
					onDragLeave={handleDragLeave}
					onDrop={(e) => handleDrop(e, column.id)}
				>
					<div className="flex items-center justify-between mb-3">
						<h3 className="font-semibold text-sm flex items-center gap-2">
							{column.label}
							{column.id === "in_review" && (
								<GitPullRequest className="w-3.5 h-3.5 text-purple-500" />
							)}
							<span className="text-xs opacity-60 bg-white/50 dark:bg-black/20 px-1.5 py-0.5 rounded">
								{todosByColumn[column.id].length}
							</span>
						</h3>
						<button
							type="button"
							onClick={() => handleOpenCreateModal(column.id)}
							className="p-1 hover:bg-white/50 dark:hover:bg-white/10 rounded transition-colors"
							title={`Add task to ${column.label}`}
						>
							<Plus className="w-4 h-4" />
						</button>
					</div>

					<div
						className={cn(
							"flex-1 space-y-2 min-h-[100px] rounded-md transition-colors",
							dragOverColumn === column.id &&
								"bg-blue-100/50 dark:bg-blue-500/10 ring-2 ring-blue-400/50 ring-dashed",
						)}
					>
						<AnimatePresence mode="popLayout">
							{todosByColumn[column.id].map((todo) => (
								<TodoCard
									key={todo._id}
									todo={todo}
									isDragging={draggedItem?._id === todo._id}
									agentStatusLabel={getAgentStatusLabel(todo)}
									onDragStart={(e) => handleDragStart(e, todo)}
									onDragEnd={() => setDraggedItem(null)}
									onClick={() => onTaskClick?.(todo)}
								/>
							))}
						</AnimatePresence>

						{todosByColumn[column.id].length === 0 && !dragOverColumn && (
							<div className="text-center text-slate-400 text-xs py-8">
								No tasks
							</div>
						)}
					</div>
				</div>
			))}

			{/* Create Task Modal */}
			<Dialog open={createModalOpen} onOpenChange={setCreateModalOpen}>
				<DialogContent className="max-w-md">
					<DialogHeader>
						<DialogTitle>
							Create Task in{" "}
							{COLUMNS.find((c) => c.id === createForColumn)?.label}
						</DialogTitle>
					</DialogHeader>
					<form onSubmit={handleCreateTask} className="space-y-4">
						<div>
							<Input
								value={newTaskTitle}
								onChange={(e) => setNewTaskTitle(e.target.value)}
								placeholder="Task title..."
								autoFocus
							/>
							<p className="text-xs text-slate-500 mt-2">
								AI will automatically generate a description based on your
								workspace context.
							</p>
						</div>
						<div className="flex justify-end gap-2">
							<Button
								type="button"
								variant="outline"
								onClick={() => setCreateModalOpen(false)}
							>
								Cancel
							</Button>
							<Button
								type="submit"
								disabled={!newTaskTitle.trim() || isCreating}
							>
								{isCreating ? "Creating..." : "Create Task"}
							</Button>
						</div>
					</form>
				</DialogContent>
			</Dialog>
		</div>
	);
}

interface TodoCardProps {
	todo: Todo;
	isDragging: boolean;
	agentStatusLabel: React.ReactNode;
	onDragStart: (e: React.DragEvent) => void;
	onDragEnd: () => void;
	onClick: () => void;
}

function TodoCard({
	todo,
	isDragging,
	agentStatusLabel,
	onDragStart,
	onDragEnd,
	onClick,
}: TodoCardProps) {
	// Query for agent run info if there's a current run
	const agentRun = useQuery(
		api.agentExecutionMutations.getAgentRunForTodo,
		todo.currentAgentRunId ? { todoId: todo._id } : "skip",
	);

	return (
		<motion.div
			layout
			initial={{ opacity: 0, scale: 0.9 }}
			animate={{ opacity: 1, scale: 1 }}
			exit={{ opacity: 0, scale: 0.9 }}
			draggable
			onDragStart={(e) => onDragStart(e as unknown as React.DragEvent)}
			onDragEnd={onDragEnd}
			onClick={onClick}
			className={cn(
				"p-3 bg-white dark:bg-slate-900 rounded-lg shadow-sm border border-slate-200/70 dark:border-white/10 cursor-grab active:cursor-grabbing hover:shadow-md transition-shadow",
				isDragging && "opacity-50",
				todo.assignee === "agent" && todo.agentType === "local" && "border-l-2 border-l-green-500",
				todo.assignee === "agent" && todo.agentType !== "local" && "border-l-2 border-l-purple-500",
				todo.agentType === "cursor" && "ring-1 ring-purple-200 dark:ring-purple-800",
				todo.agentType === "local" && "ring-1 ring-green-200 dark:ring-green-800",
			)}
		>
			<div className="flex items-start gap-2">
				<GripVertical className="w-4 h-4 text-slate-400 flex-shrink-0 mt-0.5" />
				<div className="flex-1 min-w-0">
					<p className="text-sm font-medium truncate">{todo.title}</p>
					{todo.description && (
						<p className="text-xs text-slate-500 mt-1 line-clamp-2">
							{todo.description.slice(0, 100)}
							{todo.description.length > 100 ? "..." : ""}
						</p>
					)}

					{/* Agent status and PR link */}
					<div className="flex items-center gap-2 mt-2 flex-wrap">
						{agentStatusLabel}

						{/* PR Badge */}
						{agentRun?.prUrl && (
							<a
								href={agentRun.prUrl}
								target="_blank"
								rel="noopener noreferrer"
								onClick={(e) => e.stopPropagation()}
								className={cn(
									"inline-flex items-center gap-1 text-xs px-1.5 py-0.5 rounded-full",
									agentRun.prStatus === "merged"
										? "bg-purple-100 text-purple-700 dark:bg-purple-900/50 dark:text-purple-300"
										: agentRun.prStatus === "closed"
											? "bg-red-100 text-red-700 dark:bg-red-900/50 dark:text-red-300"
											: "bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300",
								)}
							>
								<GitPullRequest className="w-3 h-3" />
								#{agentRun.prNumber}
								{agentRun.prStatus === "merged" && " merged"}
								<ExternalLink className="w-2.5 h-2.5" />
							</a>
						)}
					</div>
				</div>
			</div>
		</motion.div>
	);
}
