import { useMutation } from "convex/react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { api } from "../convex/_generated/api";
import type { Id } from "../convex/_generated/dataModel";

interface TaskCreateModalProps {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	workspaceId: Id<"workspaces">;
}

export default function TaskCreateModal({
	open,
	onOpenChange,
	workspaceId,
}: TaskCreateModalProps) {
	const [title, setTitle] = useState("");
	const [isCreating, setIsCreating] = useState(false);

	const createTodo = useMutation(api.workspaces.createWorkspaceTodo);

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		if (!title.trim()) return;

		setIsCreating(true);
		try {
			await createTodo({
				workspaceId,
				title: title.trim(),
				autoGenerateDescription: true,
			});
			setTitle("");
			onOpenChange(false);
		} catch (error) {
			console.error("Failed to create task:", error);
		} finally {
			setIsCreating(false);
		}
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className="max-w-md">
				<DialogHeader>
					<DialogTitle>Create Task</DialogTitle>
				</DialogHeader>
				<form onSubmit={handleSubmit} className="space-y-4">
					<div>
						<Input
							value={title}
							onChange={(e) => setTitle(e.target.value)}
							placeholder="Task title..."
							autoFocus
						/>
						<p className="text-xs text-slate-500 mt-2">
							AI will automatically generate a description based on your
							workspace context.
						</p>
					</div>
					<div className="flex justify-end gap-2">
						<Button
							type="button"
							variant="outline"
							onClick={() => onOpenChange(false)}
						>
							Cancel
						</Button>
						<Button type="submit" disabled={!title.trim() || isCreating}>
							{isCreating ? "Creating..." : "Create Task"}
						</Button>
					</div>
				</form>
			</DialogContent>
		</Dialog>
	);
}
